name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    env: 
      Solution_Name: Lab_5_Attempt_2.sln
      Project_Path: Lab_6/Lab_6.csproj

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: List files for debugging
      run: ls -R

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} 

    - name: Test and publish results
      run: dotnet test ${{ env.Project_Path }} 
